/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from "./routes/__root";
import { Route as EmployeeImport } from "./routes/employee";
import { Route as IndexImport } from "./routes/index";

// Create/Update Routes

const EmployeeRoute = EmployeeImport.update({
    path: "/employee",
    getParentRoute: () => rootRoute,
} as any);

const IndexRoute = IndexImport.update({
    path: "/",
    getParentRoute: () => rootRoute,
} as any);

// Populate the FileRoutesByPath interface

declare module "@tanstack/react-router" {
    interface FileRoutesByPath {
        "/": {
            id: "/";
            path: "/";
            fullPath: "/";
            preLoaderRoute: typeof IndexImport;
            parentRoute: typeof rootRoute;
        };
        "/employee": {
            id: "/employee";
            path: "/employee";
            fullPath: "/employee";
            preLoaderRoute: typeof EmployeeImport;
            parentRoute: typeof rootRoute;
        };
    }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
    "/": typeof IndexRoute;
    "/employee": typeof EmployeeRoute;
}

export interface FileRoutesByTo {
    "/": typeof IndexRoute;
    "/employee": typeof EmployeeRoute;
}

export interface FileRoutesById {
    __root__: typeof rootRoute;
    "/": typeof IndexRoute;
    "/employee": typeof EmployeeRoute;
}

export interface FileRouteTypes {
    fileRoutesByFullPath: FileRoutesByFullPath;
    fullPaths: "/" | "/employee";
    fileRoutesByTo: FileRoutesByTo;
    to: "/" | "/employee";
    id: "__root__" | "/" | "/employee";
    fileRoutesById: FileRoutesById;
}

export interface RootRouteChildren {
    IndexRoute: typeof IndexRoute;
    EmployeeRoute: typeof EmployeeRoute;
}

const rootRouteChildren: RootRouteChildren = {
    IndexRoute: IndexRoute,
    EmployeeRoute: EmployeeRoute,
};

export const routeTree = rootRoute
    ._addFileChildren(rootRouteChildren)
    ._addFileTypes<FileRouteTypes>();

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/employee"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/employee": {
      "filePath": "employee.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
